name: 'jaffle_shop'

config-version: 2
version: '1.0.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "dbt_packages"

models:
  jaffle_shop:
    stg:
      materialized: ephemeral
    marts:
      materialized: table